### ISSUE TITLE
Can't use XAML partial class page

### ISSUE THREAD

**Issue by opcodewriter** [aspnetde/MvvmNano#10]
I have a `MainView.xaml` and `MainView.cs` generated by the "Forms ContentPage Xaml" template.

I can't use the `MvvmNanoContentPage<MainViewModel>` as base class:

```
public partial class MainView : MvvmNanoContentPage<MainViewModel>
    {
        public MainView ()
        {
            InitializeComponent ();
        }
    }

```

because of the generated partial class based on XAML:

> MainView.xaml.cs(15,15): Error CS0260: Missing partial modifier on declaration of type 'MyApp.MainView'; another partial declaration of this type exists (CS0260)

I don't see a non-template MvvmNanoContentPage class which I could use.

**Comment by aspnetde** [comment]
Did you take a look into the demo app? I'm not that familiar with the way the XAML stuff works internally, but there's a working example in it (ClubPage.xaml). By looking at that example – can you tell the difference?

**Comment by opcodewriter** [comment]
OK, thanks. I see it now, the trick is the `x:TypeArguments` property:

```
<pages:MvvmNanoContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
xmlns:pages="clr-namespace:MvvmNano.Forms" 
xmlns:vm="clr-namespace:MvvmNanoDemo"
x:Class="MvvmNanoDemo.ClubPage"
x:TypeArguments="vm:ClubViewModel"
```

**Comment by opcodewriter** [comment]
However I still don't feel good about using view-model type in the view. 
View shouldn't have to know about the view-model type. 
There are few situations where that's necessary in the code behind of the view, but a simple cast does it.

**Comment by aspnetde** [comment]
It's okay to see it that way, but I strongly disagree. Having the ViewModel around in the View opens a lot of options I don't want to miss, especially type-safety. Relying on magic strings within clumpy XML isn't the way I like things to be.
