### ISSUE TITLE
Custom dependency injection 

### ISSUE THREAD

**Issue by dtila** [aspnetde/MvvmNano#16]
Hi,

I am developing a Xamarin.Forms application and for now I didn't use any Mvvm Framework in my project. However I use DryIOC as a standard container and for navigation I use the classic way by creating the VM  with the IoC and I pass the model as a parameter in the constructor or use a Initialize method defined in the VM. However the methods are called manually in order to prevent some reflection which I don't see it necessary.

However, I evaluated the MvvmCross and FreshMvvM and I didn't use them yet because they are violating SOLID principles and they bring view functionalities to the VM (which is wrong in my oppinion).

I had a look to the MvvmNano and I don't think it breaks this rule and if you keep using this design, I would be happy to work with :) However, I didn't used it yet since it's using Ninject as a container which is very slow (you can see an updated comparison here http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison )

I opened this issue as a feature, and I think adding support for custom dependency injection would be useful

**Comment by aspnetde** [comment]
Thanks for bringing this up – unfortunately I didn't receive the notification earlier.

Being able to bring your own IoC Container isn't a top priority for me, as I am fine with Ninject. But it is a valid request, which should be possible to do in the future. 

I am not planning any updates soon, so if anyone is reading this and feels the urge to implement it – PR's welcome ;).

**Comment by aspnetde** [comment]
Just found some time, and it's done:

- Core doesn't reference Ninject anymore
- Instead there's now MvvmNano.Ninject, a third library and the default IoC container
- You can bring your own, by implementing `IMvvmNanoIoCAdapter` and returning it in `MvvmNanoApplication.GetIoCAdapter()`
