### ISSUE TITLE
PCL profile

### ISSUE THREAD

**Issue by dtila** [aspnetde/MvvmNano#17]
Hi,

I am trying to install the library, but it seems that the PCL profile is quite limited. By default when you create a new project in VS 2015 is 259. According to this article http://danrigby.com/2014/04/16/xamarin-pcl-profile-notes/ , the 259 profile is supposed to replace the 78 profile which you are using. 

Since the profile 259 it seems to be the most common now (I didn;t had any issues with any library until now), do you think it would be possible to switch the target ?

**Comment by aspnetde** [comment]
I will look into it.

**Comment by krdmllr** [comment]
I had the same problem and just downgraded my solution to 78. 

I guess .NET Standard 1.0 is the way to go now https://blog.xamarin.com/net-standard-library-support-for-xamarin/
You can see the pcl/.NET Standard profile matrix at the end of this page https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by ixmrm01** [comment]
I am trying to include it in my Xamarin project but I am getting this error message:

Could not install package 'MvvmNano.Core 3.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am using Xamarin Studio Community Version 6.3 (Buld 864) on Mac.

**Comment by ixmrm01** [comment]
The ASloth comment solved my problem:

You can see the pcl/.NET Standard profile matrix at the end of this page https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by krdmllr** [comment]
@ixmrm01 you set your project target to 78?

**Comment by ixmrm01** [comment]
Yes, I did and it worked well, thanks

**Comment by krdmllr** [comment]
Version 3.0.2 supports Profile 259.
