### ISSUE TITLE
Global styles defined in App.xaml files not found 

### ISSUE THREAD

**Issue by msevestre** [aspnetde/MvvmNano#18]
In order to use MvvmNano, it is required I believe to have the App derive from `MvvmNanoApplication`

Usually, global resources are defined in the `<Application.Resources>` node
For example
```
<Application.Resources>
        <ResourceDictionary>

            <!-- Colors -->
            <Color x:Key="WhiteColor">#ffffff</Color>
            <Color x:Key="TransparentWhiteColor">#BFffffff</Color>
            <Color x:Key="BlueColor">#3063f5</Color>
...
```

The problem that I have at the moment is that if I change the base class from `Application` to `MvvmNanoApplication` as required, those static resources are not available anymore in all other pages.

I get the following error when trying to use for example the `WhiteColor`
```
Static Resource not found for key WhiteColor

...
```

It all works fine again if my `App` inherits from `Application` again.

How is this suppose to work with MvvmNano?

**Comment by krdmllr** [comment]
Hi @msevestre,

i was wondering if this issue is still relevant for you? 

I reproduced your code and everything worked.

App.xaml
```
<forms:MvvmNanoApplication xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:forms="clr-namespace:MvvmNano.Forms;assembly=MvvmNano.Forms"
             x:Class="MvvmNano.Demo.App">
    <Application.Resources>
        <ResourceDictionary>
            <Color x:Key="Purple">#cc00cc</Color>
        </ResourceDictionary>
    </Application.Resources>
</forms:MvvmNanoApplication>
```
Demo label
```
<Label Text="Welcome to Xamarin Forms!" 
        VerticalOptions="Center" 
        HorizontalOptions="Center" 
        TextColor="{StaticResource Purple}"/> 
```

**Comment by msevestre** [comment]
I moved on to using something else that was still being supported . Good luck
