### ISSUE TITLE
Could not install MvvmNano.Forms package in the Portable class library

### ISSUE THREAD

**Issue by nsabiyera** [aspnetde/MvvmNano#20]
I was quickly evaluating the framework and ran into this issue. Am using vs2017 and Xamarin Forms v2.3.4.247

![image](https://user-images.githubusercontent.com/2325053/28881646-b132091c-77a0-11e7-9931-12cc42bedefd.png)

**Comment by krdmllr** [comment]
Hey @nsabiyera 
Profile259 support will come soon. I ping you once the nuget is out.

**Comment by krdmllr** [comment]
Profile 259 is supported in the latest version 3.0.2.

**Comment by nsabiyera** [comment]
Thanks very much. I have just tested and it works with the latest version
