### ISSUE TITLE
Ninject.ActivationException : Error activating IPresenter While Unit testing

### ISSUE THREAD

**Issue by iamvignesh** [aspnetde/MvvmNano#9]
I got the below error while writing unit testing with the help of Nunit. The below error occurred just after creating the instance of my derived class of MvvmNanoContentPage Class and assigning a ViewModel to it 

Ninject.ActivationException : Error activating IPresenter
No matching bindings are available, and the type is not self-bindable.
Activation path:
  1) Request for IPresenter

Suggestions:
  1) Ensure that you have defined a binding for IPresenter.
  2) If the binding was defined in a module, ensure that the module has been loaded into the kernel.
  3) Ensure you have not accidentally created more than one kernel.
  4) If you are using constructor arguments, ensure that the parameter name matches the constructors parameter name.
  5) If you are using automatic module loading, ensure the search path and filters are correct.

**Comment by aspnetde** [comment]
The default Presenter is currently being registered in the application class (which implements MvvmNanoApplication). I guess this class isn't being used in before your test runs.

Workaround: Call `MvvmNanoIoc.RegisterAsSingleton<IPresenter>(yourPresenter);` before your test runs, where yourPresenter is an implemenation of `IPresenter` (could also be a mock by NSubstitute or some other mocking library).
